apiVersion: v1
kind: ConfigMap
metadata:
  name: draughtsman-operator
  namespace: draughtsman
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      eventer:
        github:
          organisation: {{ .Values.Installation.V1.GiantSwarm.DraughtsmanOperator.Eventer.Github.Organisation }}
      kubernetes:
        incluster: true
