apiVersion: v1
kind: ConfigMap
metadata:
  name: draughtsman-operator
  namespace: draughtsman
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      eventer:
        environment: {{ .Values.Installation.V1.GiantSwarm.DraughtsmanOperator.Eventer.Environment }}
        github:
          organisation: {{ .Values.Installation.V1.GiantSwarm.DraughtsmanOperator.Eventer.Github.Organisation }}
      installer:
        helm:
          organisation: {{ .Values.Installation.V1.GiantSwarm.DraughtsmanOperator.Installer.Helm.Organisation }}
      kubernetes:
        incluster: true
      notifier:
        slack:
          channel: {{ .Values.Installation.V1.GiantSwarm.DraughtsmanOperator.Notifier.Slack.Channel }}
