apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: draughtsman-operator-pull-secret
  namespace: draughtsman
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
