apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: draughtsman-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: draughtsman-operator
subjects:
  - kind: ServiceAccount
    name: draughtsman-operator
roleRef:
  kind: ClusterRole
  name: draughtsman-operator
  apiGroup: rbac.authorization.k8s.io
