apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: draughtsman-operator
  namespace: draughtsman
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.DraughtsmanOperator.SecretYaml | b64enc | quote }}
