apiVersion: v1
kind: Service
metadata:
  name: draughtsman-operator
  namespace: draughtsman
  labels:
    app: draughtsman-operator
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    app: draughtsman-operator
